import type { JobInput } from "../lib/types.js";
import type { LoadedSkills } from "../steps/01-read-skills.js";
import { claudeJSON } from "../claude.js";
import { PatternStore } from "./pattern-store.js";

export interface LearnedSkill {
  sourceId: string;         // e.g. "bamboo"
  draftContent: string;     // full markdown content for .draft.md
  detectionSignals: string[];
  observations: string[];
}

const LEARN_PROMPT = `
You are analyzing an unknown deployment source file to write a new source skill.

A source skill teaches future Claude instances:
1. What this tool's files look like (schema, key fields, structure)
2. How to detect this source from file content
3. How concepts map to CI/CD primitives (steps, conditions, variables, runners)
4. What boilerplate to remove

Write a thorough skill that future Claude can use without seeing the original file again.
Respond ONLY with JSON.
`;

interface LearnOutput {
  sourceId: string;
  sourceName: string;
  detectionHints: string;
  detectionSignals: string[];
  observations: string[];
  schemaSection: string;
  mappingSection: string;
  boilerplateSection: string;
}

export async function learnFromInput(
  input: JobInput,
  skills: LoadedSkills,
  patternStore: PatternStore
): Promise<LearnedSkill | null> {
  // Only learn if we have actual file content
  if (!input.files?.length) return null;

  // Find files where source was unknown / best-effort
  const unknownFiles = input.files.filter(f =>
    !patternStore.get(f.sourceId) || patternStore.get(f.sourceId)?.status === "draft"
  );

  if (!unknownFiles.length) return null;

  const file = unknownFiles[0];
  const content = file.content.slice(0, 30_000); // cap for token budget

  const raw = await claudeJSON<LearnOutput>({
    model: "claude-sonnet-4-20250514",
    system: skills.systemPrompt + "\n\n" + LEARN_PROMPT,
    user: `FILE: ${file.name}\nSOURCE_HINT: ${file.sourceId}\n\nCONTENT:\n${content}\n\nAnalyze this and produce the source skill JSON.`,
    maxTokens: 3000,
  });

  const draftContent = buildDraftSkill(raw);

  return {
    sourceId: raw.sourceId,
    draftContent,
    detectionSignals: raw.detectionSignals,
    observations: raw.observations,
  };
}

function buildDraftSkill(raw: LearnOutput): string {
  return `---
name: ${raw.sourceName}
status: draft
created_by: agent
detect_hints: ${raw.detectionHints}
---

# ${raw.sourceName} — source knowledge (draft)

> ⚠️ This skill was auto-generated by Workflow Generator Agent.
> Review carefully before relying on it for production workflows.

${raw.schemaSection}

---

## Concept mapping

${raw.mappingSection}

---

## Boilerplate to remove

${raw.boilerplateSection}
`;
}
