import type { JobInput } from "../lib/types.js";
import type { LoadedSkills } from "../steps/01-read-skills.js";
import type { GenerateResult } from "../steps/03-05-generate-validate.js";
import { GHESClient } from "../lib/ghes-client.js";
import { claudeJSON } from "../claude.js";
import { PatternStore } from "./pattern-store.js";
import { learnFromInput } from "./learn-from-input.js";

const SKILLS_PATH = process.env.SKILLS_PATH ?? "/mnt/skills";
const SKILLS_REPO = process.env.SKILLS_REPO ?? "org/deployment-ai-tools";

function ghesBaseUrl(): string {
  const url = process.env.GHES_URL ?? "https://api.github.com";
  if (url.includes("api.github.com") || url === "https://github.com") return "https://api.github.com";
  return `${url.replace(/\/$/, "")}/api/v3`;
}

function ghesClient(): GHESClient {
  return new GHESClient({ baseUrl: ghesBaseUrl(), token: process.env.GHES_BOT_TOKEN! });
}

export async function proposeNewSourceSkill(
  input: JobInput,
  skills: LoadedSkills,
  jobId: string
): Promise<{ prUrl: string; sourceId: string } | null> {
  const store = new PatternStore(SKILLS_PATH);
  const learned = await learnFromInput(input, skills, store);
  if (!learned) return null;

  const existingMem = store.get(learned.sourceId);
  if (existingMem?.prUrl) return null;

  const [owner, repo] = SKILLS_REPO.split("/");
  const branch = `skill-learn/${learned.sourceId}-${Date.now()}`;

  const pr = await ghesClient().createPR({
    owner, repo,
    title: `skill: add ${learned.sourceId} source (auto-learned from job ${jobId.slice(0, 8)})`,
    body: `## Auto-learned source skill\n\n**Source**: \`${learned.sourceId}\`\n**Job**: \`${jobId}\`\n\nReview \`skills/sources/${learned.sourceId}.draft.md\` before merging.\n\n*Auto-generated by Workflow Generator Agent*`,
    head: branch,
    base: "main",
    files: [{ path: `skills/sources/${learned.sourceId}.draft.md`, content: learned.draftContent }],
  });

  const mem = store.recordJobOutcome(learned.sourceId, jobId, true, learned.observations);
  mem.prUrl = pr.prUrl;
  store.save(mem);

  return { prUrl: pr.prUrl, sourceId: learned.sourceId };
}

export interface SkillGapAnalysis {
  summary: string;
  affectedSkill: string;
  affectedFile: string;
  proposedAddition: string;
  reason: string;
}

export async function analyzeSkillGap(
  generateResult: GenerateResult,
  input: JobInput,
  skills: LoadedSkills
): Promise<SkillGapAnalysis> {
  return claudeJSON<SkillGapAnalysis>({
    model: "claude-sonnet-4-20250514",
    system: "Analyze why workflow generation failed. Identify missing skill rules. Respond ONLY with JSON: { summary, affectedSkill, affectedFile, proposedAddition, reason }",
    user: `SKILLS:\n${skills.systemPrompt}\n\nFAILED YAML:\n${generateResult.rawYaml}\n\nSOURCE: ${input.files?.[0]?.sourceId ?? "unknown"}`,
    maxTokens: 2000,
  });
}

export async function proposeSkillFix(
  analysis: SkillGapAnalysis,
  jobId: string
): Promise<{ prUrl: string }> {
  const [owner, repo] = SKILLS_REPO.split("/");
  const pr = await ghesClient().createPR({
    owner, repo,
    title: `skill: ${analysis.summary}`,
    body: `## Skill gap fix\n\n**File**: \`${analysis.affectedFile}\`\n**Job**: \`${jobId}\`\n\n${analysis.reason}\n\n*Auto-proposed by Workflow Generator Agent*`,
    head: `skill-fix/${Date.now()}`,
    base: "main",
    files: [{ path: analysis.affectedFile, content: analysis.proposedAddition }],
  });
  return { prUrl: pr.prUrl };
}

export function recordRating(sourceId: string, jobId: string, positive: boolean): void {
  new PatternStore(SKILLS_PATH).recordJobOutcome(sourceId, jobId, positive);
}
