import type { Job, GeneratedFile } from "../lib/types.js";
import type { ValidateResult } from "./03-05-generate-validate.js";
import { GHESClient } from "../lib/ghes-client.js";
import type { PRResult } from "../lib/ghes-client.js";

// Supports both GitHub.com and GHES
function ghesBaseUrl(): string {
  const url = process.env.GHES_URL ?? "https://api.github.com";
  if (url.includes("api.github.com") || url === "https://github.com") {
    return "https://api.github.com";
  }
  // GHES: https://your-host → https://your-host/api/v3
  return `${url.replace(/\/$/, "")}/api/v3`;
}

export async function openPR(
  job: Job,
  result: ValidateResult,
  onLog: (msg: string) => void
): Promise<PRResult> {
  const client = new GHESClient({
    baseUrl: ghesBaseUrl(),
    token: process.env.GHES_BOT_TOKEN!,
  });

  const [owner, repo] = (process.env.TARGET_REPO ?? "org/repo").split("/");
  const branchName = `wf-generator/${job.id.slice(0, 8)}/${slugify(result.files[0]?.filename ?? "workflow")}`;

  onLog(`Creating branch ${branchName}...`);

  const files = result.files.map((f: GeneratedFile) => ({
    path: f.repoPath,
    content: f.content,
  }));

  const prBody = buildPRBody(job, result);

  onLog(`Opening PR in ${owner}/${repo}...`);

  const pr = await client.createPR({
    owner,
    repo,
    title: `chore: add ${result.files.map((f: GeneratedFile) => f.filename).join(", ")} via Workflow Generator`,
    body: prBody,
    head: branchName,
    base: "main",
    files,
  });

  onLog(`PR opened: ${pr.prUrl}`);
  return pr;
}

function buildPRBody(job: Job, result: ValidateResult): string {
  const plan = job.plan;
  const file = result.files[0];
  const blockers = file?.reviewNotes?.blockers ?? [];
  const assumptions = file?.reviewNotes?.assumptions ?? [];
  const secrets = file?.reviewNotes?.secretsNeeded ?? [];

  return `## Generated by Workflow Generator

**Source**: ${plan?.sourceType ?? "unknown"} — ${plan?.sourceSummary ?? ""}
**Skill**: ${plan?.skillUsed ?? "unknown"} ${plan?.skillVersion ?? ""}
**Job ID**: ${job.id}

### What this workflow does
${plan?.sourceSummary ?? ""}

${blockers.length > 0 ? `### ⚠️ Blockers — resolve before merging\n${blockers.map(b => `- ${b}`).join("\n")}` : ""}

${assumptions.length > 0 ? `### Assumptions\n${assumptions.map(a => `- ${a}`).join("\n")}` : ""}

${secrets.length > 0 ? `### Secrets to create\n${secrets.map(s => `- \`${s}\``).join("\n")}` : ""}

---
*Generated by [Workflow Generator](${process.env.NEXTAUTH_URL ?? "http://localhost:3000"})*
`;
}

function slugify(s: string): string {
  return s.replace(/\.yml$/, "").replace(/[^a-z0-9-]/gi, "-").toLowerCase();
}
